// <auto-generated />
namespace SoccerManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Clube_Possui_Jogador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clube_Possui_Jogador));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261633549_Clube_Possui_Jogador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
