// <auto-generated />
namespace SoccerManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alterar_Clube_Id_Nullavel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alterar_Clube_Id_Nullavel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051647227_Alterar_Clube_Id_Nullavel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
